# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 435)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content = QtWidgets.QStackedWidget(self.centralwidget)
        self.content.setObjectName("content")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topmenu = QtWidgets.QWidget(self.main_page)
        self.topmenu.setObjectName("topmenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topmenu)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.open_filter_button = QtWidgets.QPushButton(self.topmenu)
        self.open_filter_button.setMinimumSize(QtCore.QSize(48, 48))
        self.open_filter_button.setMaximumSize(QtCore.QSize(48, 48))
        self.open_filter_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_filter_button.setIcon(icon1)
        self.open_filter_button.setIconSize(QtCore.QSize(32, 32))
        self.open_filter_button.setObjectName("open_filter_button")
        self.horizontalLayout_2.addWidget(self.open_filter_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.add_item_button = QtWidgets.QPushButton(self.topmenu)
        self.add_item_button.setMinimumSize(QtCore.QSize(48, 48))
        self.add_item_button.setMaximumSize(QtCore.QSize(48, 48))
        self.add_item_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_item_button.setIcon(icon2)
        self.add_item_button.setIconSize(QtCore.QSize(32, 32))
        self.add_item_button.setObjectName("add_item_button")
        self.horizontalLayout_2.addWidget(self.add_item_button)
        self.manage_profiles_button = QtWidgets.QPushButton(self.topmenu)
        self.manage_profiles_button.setMinimumSize(QtCore.QSize(48, 48))
        self.manage_profiles_button.setMaximumSize(QtCore.QSize(48, 48))
        self.manage_profiles_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manage_profiles_button.setIcon(icon3)
        self.manage_profiles_button.setIconSize(QtCore.QSize(32, 32))
        self.manage_profiles_button.setObjectName("manage_profiles_button")
        self.horizontalLayout_2.addWidget(self.manage_profiles_button)
        self.open_settings_button = QtWidgets.QPushButton(self.topmenu)
        self.open_settings_button.setMinimumSize(QtCore.QSize(48, 48))
        self.open_settings_button.setMaximumSize(QtCore.QSize(48, 48))
        self.open_settings_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_settings_button.setIcon(icon4)
        self.open_settings_button.setIconSize(QtCore.QSize(32, 32))
        self.open_settings_button.setObjectName("open_settings_button")
        self.horizontalLayout_2.addWidget(self.open_settings_button)
        self.verticalLayout.addWidget(self.topmenu)
        self.content_layout = QtWidgets.QWidget(self.main_page)
        self.content_layout.setObjectName("content_layout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.content_layout)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo_if_empty = QtWidgets.QTextBrowser(self.content_layout)
        self.logo_if_empty.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logo_if_empty.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.logo_if_empty.setObjectName("logo_if_empty")
        self.horizontalLayout_3.addWidget(self.logo_if_empty)
        self.items_list = QtWidgets.QListWidget(self.content_layout)
        self.items_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.items_list.setStyleSheet("QListWidget:item {\n"
"    padding-left: 10px;\n"
"    height: 60px;\n"
"}")
        self.items_list.setIconSize(QtCore.QSize(16777215, 56))
        self.items_list.setObjectName("items_list")
        self.horizontalLayout_3.addWidget(self.items_list)
        self.verticalLayout.addWidget(self.content_layout)
        self.content.addWidget(self.main_page)
        self.add_page = QtWidgets.QWidget()
        self.add_page.setObjectName("add_page")
        self.content.addWidget(self.add_page)
        self.horizontalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GTABuyBase"))
        self.logo_if_empty.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600;\">GTABuyBase</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/img/img/icon.ico\" /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Press add button on top right corner to add item</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">To use own options create profile on profile page</span></p></body></html>"))
import gui.images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
